server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:14312/railway
    password: AkpUZiBftpVnhlYqDbTnHktMzTYFwRfz
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

#    api:
#      security:
#        token:
#          secret: ${JWT_SECRET:my-secret-key}

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
